# Generated by Django 2.2 on 2021-12-17 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20211217_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Language'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
